### PR TITLE
fix padded layouts for non-size_t indices

### LINKED ISSUE #393: Add precondition checks and mandates to test padding representability
We are not dealing with convertability properly for non-size_t indices in padded layouts and not enforcing mandates on the representability of PaddingValue:

http://eel.is/c++draft/mdspan.layout#leftpad.overview-5

Basically we need to enforce these constraints or we could potentially get subtle overflow bugs if a user is providing a smaller index_type (like char or something)

### PR DESCRIPTION
**Pull request by nmm0**
Fixes #393

### CODE REVIEW

File: tests/test_layout_padded_left.cpp [hunk 1]
```diff
@@ -1,9 +1,19 @@
...
+
+namespace {
+static bool precondition_failed = false;
+void handle_test_precondition_failure(const char *, const char *, unsigned) {
+  precondition_failed = true;
+}
+} // namespace
+
+#define MDSPAN_IMPL_PRECONDITION_VIOLATION_HANDLER(cond, file, line) \
+  handle_test_precondition_failure(cond, file, line)
```
Comment (nmm0) [inline tests/test_layout_padded_left.cpp]: Is this construct worth making more common to other tests?

**Review by crtrott — CHANGES_REQUESTED** [review]
For precondition checks all of these things need to be device functions.

File: include/experimental/__p0009_bits/utility.hpp [hunk 2]
```diff
@@ -165,6 +165,63 @@ constexpr const auto& get(const tuple<Args...>& vals) { return vals.template get
...
+    // check overflow for negative a, b
+    if (b < 0 && a < std::numeric_limits<T>::max() / b)
+      return false;
+    // check underflow for positive b, negative a
+    if (b > 0 && a < std::numeric_limits<T>::min() / b)
+      return false;
+    // check underflow for negative b, positive a
+    if (b < 0 && a > std::numeric_limits<T>::min() / b)
+      return false;
+  }
```
Comment (crtrott) [inline include/experimental/__p0009_bits/utility.hpp]: This is a function which is only used with extents right now. Let's not pay for the overhead of all these other checks for negative number combos.

```suggestion
  if constexpr (std::is_signed_v<T>) {
    if ( a < 0 || b < 0 ) return false;
  }
  return a <= std::numeric_limits<T>::max() / b;
```

**Review by crtrott — CHANGES_REQUESTED** [review]
I think we can make the check cheaper since we only use it for extents. Otherwise looks good. I made a suggestion.

File: include/experimental/__p0009_bits/utility.hpp (hunk 2 above)
Comment (crtrott) [reply include/experimental/__p0009_bits/utility.hpp]: possibly could rename function to indicate we expect positive.

**Review by crtrott — APPROVED** [review]
