### PR TITLE
Initialization, CTAD, and `[[no_unique_address]]` improvements

### LINKED ISSUE #58: `no_unique_address` emulation is broken with GCC 11
```
[14:15:39]:wash@voyager:/home/wash/development/standards/mdspan/build:127:$ ./config.bash 
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected support for C++20 standard
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS - Success
-- Using "-fconcepts" to enable concepts support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wash/development/standards/mdspan/build/tests/googletest-download
[ 11%] Performing update step for 'googletest'
[ 22%] No patch step for 'googletest'
[ 33%] No configure step for 'googletest'
[ 44%] No build step for 'googletest'
[ 55%] No install step for 'googletest'
[ 66%] No test step for 'googletest'
[ 77%] Completed 'googletest'
[100%] Built target googletest
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/bin/python3.9 (found version "3.9.0") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wash/development/standards/mdspan/build
[14:15:42]:wash@voyager:/home/wash/development/standards/mdspan/build:0:$ ./build.bash test_conversion
[ 33%] Built target gtest
[ 66%] Built target gtest_main
Scanning dependencies of target test_conversion
[ 83%] Building CXX object tests/CMakeFiles/test_conversion.dir/test_conversion.cpp.o
[100%] Linking CXX executable test_conversion
/usr/bin/ld: CMakeFiles/test_conversion.dir/test_conversion.cpp.o: in function `std::experimental::detail::stride_storage_impl<std::experimental::extents<2ul, 3ul>, std::integer_sequence<unsigned long, 0ul, 1ul>, std::experimental::detail::layout_right_idx_conditional>::stride_storage_impl(std::experimental::extents<2ul, 3ul> const&)':
test_conversion.cpp:(.text._ZNSt12experimental6detail19stride_storage_implINS_7extentsIJLm2ELm3EEEESt16integer_sequenceImJLm0ELm1EEENS0_28layout_right_idx_conditionalEEC2ERKS3_[_ZNSt12experimental6detail19stride_storage_implINS_7extentsIJLm2ELm3EEEESt16integer_sequenceImJLm0ELm1EEENS0_28layout_right_idx_conditionalEEC2ERKS3_]+0x1f): undefined reference to `std::experimental::detail::__no_unique_address_emulation<std::experimental::extents<2ul, 3ul>, 0ul, void>::__no_unique_address_emulation(std::experimental::extents<2ul, 3ul> const&)'
collect2: error: ld returned 1 exit status
make[3]: *** [tests/CMakeFiles/test_conversion.dir/build.make:105: tests/test_conversion] Error 1
make[2]: *** [CMakeFiles/Makefile2:252: tests/CMakeFiles/test_conversion.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:259: tests/CMakeFiles/test_conversion.dir/rule] Error 2
make: *** [Makefile:207: test_conversion] Error 2
[14:15:49]:wash@voyager:/home/wash/development/standards/mdspan/build:0:$ git show HEAD
commit 96d786a90f2835254157e2e48378b21339af3b8b (HEAD -> stable, origin/stable, origin/HEAD, brycelelbach/stable)
Merge: 690c52c 099da35
Author: Christian Trott <crtrott@sandia.gov>
Date:   Mon Jun 7 22:59:48 2021 -0600

    Merge pull request #53 from brycelelbach/brycelelbach/P0009R12
    
    Explicit constructor fixes, deduction guides, and list initialization/CTAD tests

```

No clue what's going on here.

### PR DESCRIPTION
**Pull request by brycelelbach**
Fixes #58.

### CODE REVIEW

**Comment by crtrott** [comment]
probably needs a rebase?

File: benchmarks/copy/copy_layout_stride.cpp [hunk 1]
```diff
@@ -335,7 +335,7 @@ void BM_Raw_Copy_2D(benchmark::State& state, T, size_t x, size_t y) {
   auto buffer = std::make_unique<value_type[]>(x * y);
   {
     // just for setup...
-    auto wrapped = stdex::mdspan<T, stdex::dynamic_extent>{buffer.get(), x * y};
+    auto wrapped = stdex::mdspan<T, stdex::extents<1>>{buffer.get(), x * y};
```
Comment (crtrott) [inline benchmarks/copy/copy_layout_stride.cpp]: should be dextents ...

Comment (brycelelbach) [reply benchmarks/copy/copy_layout_stride.cpp]: Fixed

**Comment by brycelelbach** [comment]
Rebased.

File: benchmarks/stencil/cuda/stencil_3d_cuda.cu [hunk 2]
```diff
@@ -204,7 +206,7 @@ void BM_Raw_Cuda_Stencil_3D_right(benchmark::State& state, T, SizeX x, SizeY y,
   value_type* data_o = nullptr;
   {
     // just for setup...
-    auto wrapped = stdex::mdspan<T, stdex::dynamic_extent>{};
+    auto wrapped = stdex::mdspan<T, stdex::extents<1>>{};
```
Comment (crtrott) [inline benchmarks/stencil/cuda/stencil_3d_cuda.cu:209]: needs to be dextents ...

Comment (crtrott) [inline benchmarks/stencil/cuda/stencil_3d_cuda.cu]: Needs to be dextents

File: benchmarks/stencil/stencil_3d.cpp [hunk 3]
```diff
@@ -100,17 +102,17 @@ void BM_MDSpan_Stencil_3D(benchmark::State& state, MDSpan, DynSizes... dyn) {
...
+MDSPAN_BENCHMARK_ALL_3D(BM_MDSpan_Stencil_3D, right_, rmdspan, 400, 400, 400);
 MDSPAN_BENCHMARK_ALL_3D(BM_MDSpan_Stencil_3D, left_, lmdspan, 400, 400, 400);
 
 //================================================================================
 
 template <class T, class SizeX, class SizeY, class SizeZ>
 void BM_Raw_Stencil_3D_right(benchmark::State& state, T, SizeX x, SizeY y, SizeZ z) {
 
-  using MDSpan = stdex::mdspan<T, stdex::dynamic_extent, stdex::dynamic_extent, stdex::dynamic_extent>;  
+  using MDSpan = stdex::mdspan<T, stdex::extents<3>>;
```
Comment (crtrott) [inline benchmarks/stencil/stencil_3d.cpp]: needs to be dextents

File: include/experimental/__p0009_bits/config.hpp [hunk 4]
```diff
@@ -61,13 +60,15 @@
 #define _MDSPAN_CPLUSPLUS __cplusplus
 #endif
 
-static_assert(_MDSPAN_CPLUSPLUS >= 201102L, "MDSpan requires C++11 or later.");
+static_assert(_MDSPAN_CPLUSPLUS >= 201102L, "mdspan requires C++11 or later.");
```
Comment (crtrott) [inline include/experimental/__p0009_bits/config.hpp]: lets switch this to C++14 here. No need to support 11

File: include/experimental/__p0009_bits/layout_left.hpp [hunk 5]
```diff
@@ -63,87 +64,111 @@ struct layout_left_idx_conditional {
...
+    // should work. But, in our implementation we've chosen to leave the primary
+    // template empty and put the implementation in the specialization below.
+    // Unfortunately, it seems that the primary template is the one used for
+    // deduction.
+    //
+    // But, by cleverly adding a constructor declaration to the primary that
+    // serves as a pseudo deduction guide, we can get the automatic deduction
+    // guide to do the right thing.
+    MDSPAN_INLINE_FUNCTION
+    constexpr mapping(Extents const&) noexcept = delete;
```
Comment (crtrott) [inline include/experimental/__p0009_bits/layout_left.hpp]: isn't that constructor supposed to exist??

Comment (crtrott) [reply include/experimental/__p0009_bits/layout_left.hpp]: oh wait are we going via some partial specialization below?

File: include/experimental/__p0009_bits/compressed_pair.hpp [hunk 6]
```diff
@@ -0,0 +1,218 @@
...
+//@HEADER
+*/
+
+#pragma once
+
+#include "macros.hpp"
+#include "trait_backports.hpp"
+
+#if !defined(_MDSPAN_USE_ATTRIBUTE_NO_UNIQUE_ADDRESS)
+#  include "no_unique_address.hpp"
```
Comment (nliber) [inline include/experimental/__p0009_bits/compressed_pair.hpp:50]: That's a weird spacing for `#  include` (in many places for this header only).

**Review by nliber — DISMISSED** [review]

**Comment by brycelelbach** [comment]
Making CTAD work for the layout mappings was interesting, because they are member template classes or aliases. I changed them to not be aliases, because I wanted to avoid depending on alias template deduction, which is C++20 only and not available everywhere yet. However, this has one notable downside: [GCC currently rejects deduction guides for member template classes](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100983), so if the layout mappings are member template classes instead of aliases, we can't write deduction guide for them.

For `layout_left` and `layout_right`, the automatic deduction guides should work - they have a single template parameter which is an extents object and they have a constructor that takes a single extents object. However, we implement the layout mappings as a template specialization, and CTAD looks at the primary template for deduction. The primary template for the layout mappings was previously declared and not defined, and now just contains a `static_assert`.

We could refactor the code to not implement the mappings as a template specialization, but that seemed like a bunch of work. Without that refactoring, we need a deduction guide to make `layout_left` and `layout_right` work, but as stated earlier, I couldn't add one if they were member class templates because GCC is broken, and I didn't want to make them member alias templates because I'd have to rely on alias template argument deduction which is C++20 only and only supported by GCC. However, I was able to workaround this problem by introducing deleted constructors to the primary template.

**Comment by brycelelbach** [comment]
> We could refactor the code to not implement the mappings as a template specialization, but that seemed like a bunch of work.

Turns out this was a lot less work than I thought, so I did it. Now the layout mappings are not implemented as partial specializations, but instead as primary templates, which makes enabling automatic deduction guides a lot simpler.

File: include/experimental/__p0009_bits/depend_on_instantiation.hpp [hunk 7]
```diff
@@ -41,18 +41,21 @@
 //@HEADER
 */
 
-#include <experimental/mdspan>
+#pragma once
```
Comment (dalg24) [inline include/experimental/__p0009_bits/depend_on_instantiation.hpp]: That's the silliest diff I have seen in a while :/
You broke GitHub

File: include/experimental/__p0009_bits/compressed_pair.hpp (hunk 6 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/compressed_pair.hpp:50]: We do it in `config.hpp`. I'm not a fan, I was just following what `config.hpp` does.

File: include/experimental/__p0009_bits/layout_right.hpp [hunk 8]
```diff
@@ -46,6 +46,7 @@
 #include "macros.hpp"
 #include "fixed_layout_impl.hpp"
 #include "trait_backports.hpp"
+#include "depend_on_instantiation.hpp"
```
Comment (dalg24) [inline include/experimental/__p0009_bits/layout_right.hpp]: Where is it used?

**Review by crtrott — CHANGES_REQUESTED** [review]
Largely ok other than some dextents missing the d. We need to test on more compilers first, but I think this is good.

**Review by crtrott — CHANGES_REQUESTED** [review]
Still missing a couple of "d"s

File: include/experimental/__p0009_bits/layout_stride.hpp [hunk 9]
```diff
@@ -48,6 +48,12 @@
 #include "static_array.hpp"
 #include "extents.hpp"
 #include "trait_backports.hpp"
+#include "depend_on_instantiation.hpp"
```
Comment (dalg24) [inline include/experimental/__p0009_bits/layout_stride.hpp]: Where is it used?

File: include/experimental/__p0009_bits/depend_on_instantiation.hpp (hunk 7 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/depend_on_instantiation.hpp]: Not sure what you mean?

File: include/experimental/__p0009_bits/layout_right.hpp (hunk 8 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/layout_right.hpp]: This was used in a static_assert that's been removed, it can probably be removed as well.

File: include/experimental/__p0009_bits/layout_stride.hpp (hunk 9 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/layout_stride.hpp]: This was used in a static_assert that's been removed, it can probably be removed as well.

File: include/experimental/__p0009_bits/layout_left.hpp (hunk 5 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/layout_left.hpp]: Nope, I refactored my way out of this. It's no longer needed.

File: include/experimental/__p0009_bits/config.hpp (hunk 4 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/config.hpp]: Done.

File: benchmarks/stencil/stencil_3d.cpp (hunk 3 above)
Comment (brycelelbach) [reply benchmarks/stencil/stencil_3d.cpp]: Done.

File: benchmarks/stencil/cuda/stencil_3d_cuda.cu (hunk 2 above)
Comment (brycelelbach) [reply benchmarks/stencil/cuda/stencil_3d_cuda.cu]: Done.

File: include/experimental/__p0009_bits/config.hpp (hunk 4 above)
Comment (brycelelbach) [reply include/experimental/__p0009_bits/config.hpp]: Done.

File: include/experimental/__p0009_bits/depend_on_instantiation.hpp (hunk 7 above)
Comment (dalg24) [reply include/experimental/__p0009_bits/depend_on_instantiation.hpp]: The diff displayed is absurd because git thinks that `tests/test_ctors.cpp -> .../__p0009_bits/depend_on_instantiation.hpp`

Comment (dalg24) [reply include/experimental/__p0009_bits/depend_on_instantiation.hpp]: Your code is fine ;)

File: include/experimental/__p0009_bits/layout_right.hpp (hunk 8 above)
Comment (dalg24) [reply include/experimental/__p0009_bits/layout_right.hpp]: You forgot to remove that guy

Comment (dalg24) [reply include/experimental/__p0009_bits/layout_right.hpp]: Nevermind you fixed it

**Review by crtrott — CHANGES_REQUESTED** [review]
This looks good. but thanks to lack of proper testing we broke C++14 compilation already before so I can't check whether this does further damage ....

Looking into this now. 1e40f4eeab3281103 still worked, cc22d07f566 is broken.

**Comment by crtrott** [comment]
looks like the compiler is lying about the _v stuff available??

**Comment by crtrott** [comment]
I was able to fix the GCC 5 build issue fairly simple, since it was broken before I think we can do it as a separate PR. still having a problem with Intel compiler (17)

**Comment by crtrott** [comment]
Intel 17 build also broke with the 1e40f4e SHA so no hold up from that either I think.

File: .github/workflows/single-header.yml [hunk 10]
```diff
@@ -0,0 +1,23 @@
+name: Build Single Header
+
+on:
+  push:
+    branches:
+      - stable
+  pull_request:
```
Comment (dalg24) [inline .github/workflows/single-header.yml]: I think we need to remove this line

**Review by crtrott — APPROVED** [review]
