### PR TITLE
Fix nvc++ test build error

### LINKED ISSUE #148: nvc++ build error test_contiguous_layouts.cpp
Building `tests/test_contiguous_layouts.cpp` with nvc++ 22.5-0 fails, because the type lists are too long.  Work-around is to split up the type lists.

Errors look like this (with much more text than this):
```
".../tests/googletest-src/googletest/include/gtest/internal/gtest-internal.h", line 741: error: excessive recursion at instantiation of function "testing::internal::TypeParameterizedTest<Fixture, TestSel, Types>::Register [with Fixture=TestLayoutConversion, 
```

### PR DESCRIPTION
**Pull request by mhoemmen**
Building tests/tests_contiguous_layouts.cpp fails with nvc++ 22.5-0.  This commit fixes that.

Fixes #148.

### CODE REVIEW

File: tests/test_contiguous_layouts.cpp [hunk 1]
```diff
@@ -335,7 +357,39 @@ struct TestLayoutConversion<
   }
 };
 
-TYPED_TEST_SUITE(TestLayoutConversion, layout_conversion_test_types);
+// We can't reuse TestLayoutConversion directly for multiple suites,
+// because this results in duplicate test names.
+// However, creating an alias for each suite works around this.
+
+TYPED_TEST_SUITE(TestLayoutConversion, layout_conversion_test_types_left_to_left);
```
Comment (crtrott) [inline tests/test_contiguous_layouts.cpp:364]: Why not use an alias for this too, so that the testnames show up systematically?

File: tests/test_contiguous_layouts.cpp [hunk 2]
```diff
@@ -365,7 +419,7 @@ TYPED_TEST(TestLayoutConversion, implicit_conversion) {
   #endif
     map1 = typename TestFixture::map_1_t(map2);
 
-  for(size_t r=0; r<this->exts1.rank(); r++) {
+  for(size_t r=0; r != this->exts1.rank(); ++r) {
```
Comment (crtrott) [inline tests/test_contiguous_layouts.cpp:422]: what is this?

**Review by crtrott — CHANGES_REQUESTED** [review]

**Review by nliber — APPROVED** [review]

File: tests/test_contiguous_layouts.cpp (hunk 2 above)
Comment (mhoemmen) [reply tests/test_contiguous_layouts.cpp:422]: It prevents an nvc++ build warning.

File: tests/test_contiguous_layouts.cpp (hunk 1 above)
Comment (crtrott) [reply tests/test_contiguous_layouts.cpp:364]: Mark said nvc++ fails if he uses an alias here too.

**Review by crtrott — APPROVED** [review]

File: tests/test_contiguous_layouts.cpp (hunk 1 above)
Comment (mhoemmen) [reply tests/test_contiguous_layouts.cpp:364]: Right -- not sure why.  I'll experiment a bit once PR #147 lands.  Thanks!
